M48
; DRILL file {KiCad (6.0.10)} date Mon Feb 27 01:31:48 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-27T01:31:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1201
%
G90
G05
T1
X4.9567Y-3.4824
X5.9414Y-2.9233
X6.9257Y-3.4828
T0
M30
